services:
  mysql:
    image: mysql:9.3.0
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: leasing
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - 3308:3306
    volumes:
      - ./BDD:/docker-entrypoint-initdb.d
      - data:/data/bdd

  # python:
  #   build: ./Calculo
  #   image: python:3.10-alpine3.22
  #   ports:
  #     - 3000:3000

volumes:
  data: